import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CURIOSENSE INNOVATION PRIVATE LIMITED',
  description: 'Generated by create next app',
  
  icons: {
    icon: 'https://i.ibb.co/fXPdQwX/logo.jpg',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body suppressHydrationWarning={true}>
        <AuthProvider>

          {children}
        </AuthProvider>




        {/* <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></script> */}
        {/* <script src="node_modules/@material-tailwind/html/scripts/collapse.js"></script> */}
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
      </body>
    </html>
  )
}
